---
runs:
  using: "composite"
  steps:
    - run: echo action1
      shell: bash
    - uses: ./.github/actions/action2
    - run: echo action1 middle
      shell: bash
    - uses: ./.github/actions/action2
      with:
        somelist: '["first_elem", "second_elem"]'
    - run: echo action1 end
      shell: bash