---
name: "Report"
inputs:
  action:
    required: true
  actor:
    required: true
  base_ref:
    required: true
  sha:
    required: true
# outputs:
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.action }}
      shell: bash
    - run: echo ${{ inputs.actor }}
      shell: bash
    - run: echo ${{ inputs.base_ref }}
      shell: bash
    - run: echo ${{ inputs.sha }}
      shell: bash
