---
# inputs:
#   action:
#     required: true
#   base_ref:
#     required: true
#   sha:
#     required: true
# outputs:
runs:
  using: "composite"
  steps:
    - run: echo action=${{ github.action }}
      shell: bash
    - run: echo actor=${{ github.actor }}
      shell: bash
    - run: echo sha=${{ github.sha }}
      shell: bash
    - run: echo secret=${{ github.secrets.USELESS_SECRET }}
      shell: sh
    - run: echo secret2=${{ secrets.USELESS_SECRET }}
      shell: sh