name: "Automerge"

"on":
  pull_request:
    types:
      - opened
    paths:
      - good/*
      - good/**

# permissions:
#   contents: read
#   packages: read

jobs:
  automerge:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      automerge:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Report diff
        run: gh pr diff --name-only ${{ github.event.number }}

      - name: Report labels
        run: gh api repos/amarao/debug/pulls/${{ github.event.number }} --jq '.labels.[].name'

      - name: Validate changes scope
        run: |
          import subprocess
          import os
          import sys

          cmd = "gh pr diff --name-only ${{ github.event.number }}"
          files = subprocess.check_output(cmd, shell=True)

          content_good = False
          label_good = False
          for name in files.decode("utf-8").splitlines():
            if not name.startswith("good/"):
              print(f"Found {name}. Automerge is not possible")
              break
          else:
            print("Content OK")
            content_good = True

          cmd = "gh api repos/amarao/debug/pulls/${{ github.event.number }} --jq '.labels.[].name'"
          labels = subprocess.check_output(cmd, shell=True)
          label_good == "automerge" in labels.decode('UTF-8')
          with open(os.environ["GITHUB_OUTPUT"], "w") as f:
                if content_good:
                  f.write("content=ok\n")
                else:
                  f.write("content=bad\n")
                if label_good:
                  f.write("label=good\n")
                else:
                  f.write("label=bad\n")
        shell: python {0}
        id: check

      - name: Merge
        if: "${{ steps.check.outputs.content == 'good' &&  steps.check.outputs.label == 'good' }}"
        run: |
          # gh pr merge ${{ github.event.number }} --auto -d --merge
          # gh pr comment ${{ github.event.number }} --body "This PR was automerged."
          gh pr comment ${{ github.event.number }} --body "I really want to merge this, but grumpy operators keep me on leash."

      - name: Refuse to merge because of the content
        if: "${{ steps.check.outputs.content == 'good' }}"
        run: gh pr comment ${{ github.event.number }} --body "This PR can not be merged automatically, as it contains non-trivial changes"

      - name: Refuse to merge because of the content
        if: "${{ steps.check.outputs.label == 'good' }}"
        run: gh pr comment ${{ github.event.number }} --body "This PR did not have 'automerge' label at the moment of creation, so I won't merge it."
