---
name: Autodeploy

"on":
    push:
jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - name: install
        run: sudo pip install ansible
      - name: install apt
        run: |
          sudo apt update
          sudo apt install -y python3-libvirt libvirt-clients libvirt-daemon libvirt-daemon-system libvirt-daemon-driver-qemu
      - name: VM
        run: ansible-playbook -i virt_inv.yaml libvirt.yaml
