name: Context

on:
  workflow_dispatch:
  push:
jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout infra repo
        uses: actions/checkout@v2
      - name: Report
        uses: ./.github/actions/report
        with:
          actor: ${{ github.actor }}
          sha: ${{ github.sha }}
          target_repo: foo
          target_ref: '${{ secrets.USELESS_SECRET }}'
          