name: Context

on:
  workflow_dispatch:
  push:
jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Report
        run: |
          echo github.action=${{ github.action }}
          echo github.actor=${{ github.actor }}
          echo github.base_ref=${{ github.base_ref }}
          echo github.sha=${{ github.sha }}