name: Context

on:
  workflow_dispatch:
  push:
jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - uses: ./.github/actions/report
        with:
          action: ${{ github.action }}
          actor: ${{ github.actor }}
          base_ref: ${{ github.base_ref }}
          sha: ${{ github.sha }}