name: "deploy"

on:
  workflow_dispatch:
  push:
    branch:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Report
        run: cat good/foo
