# This is a basic workflow to help you get started with Actions

name: external worker

# Controls when the action will run.
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Install dependencies
        run: sudo apt install -y python3 python3-jwt python3-requests

      - name: Checkout
        uses: actions/checkout@v2