# This is a basic workflow to help you get started with Actions

name: external worker

# Controls when the action will run.
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y python3-pip

      - name: Install req
        run: sudo pip install -r requirements.txt
      - name: Checkout
        uses: actions/checkout@v2