---
name: test

"on":
  workflow_dispatch:
    inputs:
      foo:
        description: foo
        required: true
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ::warning ::something fishy
      - run: |
          import os
          print(repr(os.environ.get("INPUTS")))
        shell: /usr/bin/python3 {0}

        env:
          INPUTS: ${{ toJSON(inputs) }}
