---
name: test

"on":
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: action with false
        uses: ./.github/actions/action2
        with:
          foo: false
      - name: action with true
        uses: ./.github/actions/action2
        with:
          foo: true
      - name: action with default
        uses: ./.github/actions/action2
      - run: echo ok
