---
name: test

"on":
  workflow_dispatch:
    inputs:
      foo:
        description: foo
        required: true
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: export
        run: |
          echo foo=bar >> "$GITHUB_ENV"
          echo foobar=foobar >> "$GITHUB_ENV"
          echo ${{ secrets.FOOBAR }}
      - name: test
        run: echo ${{ env.foo }} ${{ env.foobar }}
      - name: test2
        run: echo $foo $foobar
      - name: Login to docker
        uses: docker/login-action@v2.1.0
        with:
          username: "${{ env.foo }}"
          password: "${{ env.foobar }}"