---
name: test

"on":
  workflow_dispatch:
    inputs:
      foo:
        description: foo
        required: true
  push:

jobs:
  prep:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      transfer_secret: ${{ steps.password.outputs.password }}
      foobar: ${{ steps.foobar.outputs.foobar }}
    steps:
      - name: mask
      - run: echo password=$(echo ${{ secrets.PASSWORD }} | base64) >> $GITHUB_OUTPUT
        id: password
      - run: echo foobar=FOOBAR >> $GITHUB_OUTPUT
        id: foobar
  test:
    runs-on: ubuntu-latest
    needs:
      - prep
    steps:
      - name: mask
        run: |
          echo ::add-mask::${{ needs.prep.outputs.transfer_secret }}
          echo ::add-mask::$( echo ${{ needs.prep.outputs.transfer_secret }}|base64 -d)
      - run: echo ${{ needs.prep.outputs.transfer_secret }} | base64 -d
      - run: echo ...${{ needs.prep.outputs.foobar }}...
      - run: |
          for a in `seq 1 10`; do
              echo -e ::warning ::warning here, number $a
          done
