---
name: test

"on":
  workflow_dispatch:
    inputs:
      foo:
        description: foo
        required: true
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for a in `seq 1 10000`; do
              echo -e ::warning ::warning here, number $a
          done
      - run: |
          for a in `seq 1 10000`; do
              echo -e ::notice ::changed something here, number $a \\n second line $a
          done
        shell: bash

      - run: |
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo
          for a in `seq 1 10000`; do
              echo "* hello $a" >> $GITHUB_STEP_SUMMARY
          done
        shell: bash
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '#### Second job' >> $GITHUB_STEP_SUMMARY
          echo
          for a in `seq 1 10000`; do
              echo "* second $a" >> $GITHUB_STEP_SUMMARY
          done
        shell: bash
