---
name: test

"on":
  workflow_dispatch:
    inputs:
      foo:
        default: auto
        required: true
        description: foo
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - run: echo ${{ github.event.inputs.foo }}
