---
name: Nested actions

"on":
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: action
        uses: ./.github/actions/action1
      - name: final
        run: echo final