# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run.
on:
  workflow_dispatch:
jobs:
  clone:
    runs-on: ubuntu-latest
    container:
      image: amarao/ansido:latest
    steps:
      - name: version
        run: ansible --version
